### ISSUE TITLE
Puma doesnt restart on deploy

### ISSUE THREAD

**Issue by phongsi** [ajgon/opsworks_ruby#127]
on a deploy when puma is already running, the opsworks logs show
```
[2017-11-19T17:06:59+00:00] INFO: Processing execute[stop puma] action run (opsworks_ruby::deploy line 53)
[2017-11-19T17:06:59+00:00] INFO: execute[stop puma] ran successfully
[2017-11-19T17:06:59+00:00] INFO: Processing execute[start puma] action run (opsworks_ruby::deploy line 53)
[2017-11-19T17:07:07+00:00] INFO: execute[start puma] ran successfully
```

however, the puma process is no longer running. I think it has to do with the after_deploy hook in the appserver base driver when it does a stop and a start [here](https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_appserver_base.rb#L21) This happens too quickly and the start fails because the previous server hasnt shut down yet.
```
/srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/lib/puma/binder.rb:363:in `add_unix_listener': There is already a server bound to: /srv/www/application/shared/sockets/puma.sock (RuntimeError)
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/lib/puma/binder.rb:141:in `block in parse'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/lib/puma/binder.rb:88:in `each'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/lib/puma/binder.rb:88:in `parse'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/lib/puma/runner.rb:144:in `load_and_bind'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/lib/puma/cluster.rb:397:in `run'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/lib/puma/launcher.rb:183:in `run'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/lib/puma/cli.rb:77:in `run'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/gems/puma-3.10.0/bin/puma:10:in `<top (required)>'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/bin/puma:22:in `load'
	from /srv/www/application/shared/vendor/bundle/ruby/2.3/bin/puma:22:in `<main>'```

**Comment by phongsi** [comment]
I looked through the aws opsworks cookbooks. It looks like they just do a restart on whatever appserver on deploy instead of a stop start.

I tested the restart command and that works fine on deploy.
