### ISSUE TITLE
Removing path for bundle and gem, forced everywhere, still gives me errors

### ISSUE THREAD

**Issue by HelioCampos** [ajgon/opsworks_ruby#143]
Hi Guys,

I see the path `/usr/local/bin/` forced on several places. Why is that?

I'm using [ruby_rbenv](https://github.com/sous-chefs/ruby_rbenv) to install a ruby+gem+bundle locally for a specific user but these forced paths are forcing me to redact the cookbook to remove them and, in the process, creating new error like in this rails migration. Are they really necessary? Can't a file named .ruby-version be used on each project to choose the version of the ruby/bundle/gem?
I tried to change the migration command to this:
```
case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in
   *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; 
   *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";;
esac;
```
1. I had to use sudo and ask it to reset the env variables (with -i) to the $PATH of the user work;
2. Reseting the ENV vars made me change directory to the users' home so I had to use the cd $PWD to use the actual directory;

But I'm still getting the following error:
```
[2018-01-23T18:32:03+00:00] INFO: deploy[<REDACTED>] queueing checkdeploy hook /srv/www/<REDACTED>/releases/20180123183147/deploy/before_migrate.rb
[2018-01-23T18:32:03+00:00] INFO: Processing execute[bundle_install] action run (/var/chef/runs/1a303e81-6771-4a6b-b729-2709c905217f/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/helpers.rb line 102)
[2018-01-23T18:33:56+00:00] INFO: execute[bundle_install] ran successfully
[2018-01-23T18:33:56+00:00] INFO: deploy[<REDACTED>] made pre-migration symlinks
[2018-01-23T18:33:57+00:00] INFO: deploy[<REDACTED>] set user to deploy
[2018-01-23T18:33:57+00:00] INFO: deploy[<REDACTED>] migrating deploy with environment <REDACTED>
[2018-01-23T18:34:07+00:00] WARN: Error on deploying /srv/www/<REDACTED>/releases/20180123183147: Expected process to exit with [0], but received '1'
---- Begin output of case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; ----
STDOUT: 
STDERR: rake aborted!
NameError: uninitialized constant Bullet
/srv/www/<REDACTED>/releases/20180123183147/config/environments/development.rb:45:in `block in <top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/railtie.rb:210:in `instance_eval'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/railtie.rb:210:in `configure'
/srv/www/<REDACTED>/releases/20180123183147/config/environments/development.rb:1:in `<top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:597:in `each'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:597:in `block in <class:Engine>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/srv/www/<REDACTED>/releases/20180123183147/config/environment.rb:5:in `<top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
---- End output of case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; ----
Ran case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; returned 1
[2018-01-23T18:34:07+00:00] INFO: Removing failed deploy /srv/www/<REDACTED>/releases/20180123183147
 
================================================================================
Error executing action `deploy` on resource 'deploy[<REDACTED>]'
================================================================================
 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; ----
STDOUT: 
STDERR: rake aborted!
NameError: uninitialized constant Bullet
/srv/www/<REDACTED>/releases/20180123183147/config/environments/development.rb:45:in `block in <top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/railtie.rb:210:in `instance_eval'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/railtie.rb:210:in `configure'
/srv/www/<REDACTED>/releases/20180123183147/config/environments/development.rb:1:in `<top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:597:in `each'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:597:in `block in <class:Engine>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/srv/www/<REDACTED>/releases/20180123183147/config/environment.rb:5:in `<top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
---- End output of case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; ----
Ran case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; returned 1
 
Resource Declaration:
---------------------
# In /var/chef/runs/1a303e81-6771-4a6b-b729-2709c905217f/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb
 
23:   deploy application['shortname'] do
24:     deploy_to deploy_dir(application)
25:     user node['deployer']['user'] || 'root'
26:     group www_group
27:     environment application['environment'].merge(framework.out[:deploy_environment] || {})
28: 
29:     if globals(:rollback_on_error, application['shortname']).nil?
30:       rollback_on_error node['defaults']['global']['rollback_on_error']
31:     else
32:       rollback_on_error globals(:rollback_on_error, application['shortname'])
33:     end
34: 
 
Compiled Resource:
------------------
# Declared in /var/chef/runs/1a303e81-6771-4a6b-b729-2709c905217f/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:23:in `block in from_file'
 
deploy("<REDACTED>") do
action [:deploy]
updated true
updated_by_last_action true
retries 0
retry_delay 2
default_guard_interpreter :default
deploy_to "/srv/www/<REDACTED>"
environment {<REDACTED>}
repository_cache "cached-copy"
purge_before_symlink ["log", "tmp/cache", "tmp/pids", "public/system", "public/assets"]
create_dirs_before_symlink ["tmp", "public", "config", "../../shared/cache", "../../shared/assets"]
symlink_before_migrate {"config/database.yml"=>"config/database.yml"}
symlinks {"system"=>"public/system", "assets"=>"public/assets", "cache"=>"tmp/cache", "pids"=>"tmp/pids", "log"=>"log"}
revision "staging-deploy"
migrate true
rollback_on_error true
remote "origin"
enable_submodules true
scm_provider Chef::Provider::Git
keep_releases 5
enable_checkout true
checkout_branch "deploy"
declared_type :deploy
cookbook_name "opsworks_ruby"
recipe_name "deploy"
user "deploy"
git_ssh_wrapper "/tmp/ssh-git-wrapper.sh"
repo "git@github.com:<REDACTED>-sa/<REDACTED>.git"
migration_command "case $(sudo -i -u deploy bash -c \"cd $PWD; bundle exec rake db:version 2>&1\") in *\"ActiveRecord::NoDatabaseError\"*) sudo -i -u deploy bash -c \"cd $PWD; bundle exec rake db:setup\";; *) sudo -i -u deploy bash -c \"cd $PWD; bundle exec rake db:migrate\";; esac;"
before_migrate #<Proc:0x000000024cbf38@/var/chef/runs/1a303e81-6771-4a6b-b729-2709c905217f/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:64>
before_symlink #<Proc:0x000000024cb060@/var/chef/runs/1a303e81-6771-4a6b-b729-2709c905217f/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:73>
before_restart #<Proc:0x000000024ca9d0@/var/chef/runs/1a303e81-6771-4a6b-b729-2709c905217f/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:83>
after_restart #<Proc:0x000000024ca390@/var/chef/runs/1a303e81-6771-4a6b-b729-2709c905217f/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:91>
timeout 600
shared_path "/srv/www/<REDACTED>/shared"
destination "/srv/www/<REDACTED>/shared/cached-copy"
current_path "/srv/www/<REDACTED>/current"
end
 
Platform:
---------
x86_64-linux
 
[2018-01-23T18:34:07+00:00] INFO: Running queued delayed notifications before re-raising exception
[2018-01-23T18:34:07+00:00] INFO: template[nginx.conf] sending reload action to service[nginx] (delayed)
[2018-01-23T18:34:07+00:00] INFO: Processing service[nginx] action reload (opsworks_ruby::deploy line 39)
[2018-01-23T18:34:08+00:00] INFO: service[nginx] reloaded
[2018-01-23T18:34:08+00:00] INFO: template[/etc/nginx/sites-available/<REDACTED>.conf] sending restart action to service[nginx] (delayed)
[2018-01-23T18:34:08+00:00] INFO: Processing service[nginx] action restart (opsworks_ruby::deploy line 39)
[2018-01-23T18:34:08+00:00] INFO: service[nginx] restarted
[2018-01-23T18:34:08+00:00] ERROR: Running exception handlers
[2018-01-23T18:34:08+00:00] ERROR: Exception handlers complete
[2018-01-23T18:34:08+00:00] FATAL: Stacktrace dumped to /var/chef/runs/1a303e81-6771-4a6b-b729-2709c905217f/local-mode-cache/cache/chef-stacktrace.out
[2018-01-23T18:34:08+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-01-23T18:34:08+00:00] ERROR: deploy[<REDACTED>] (opsworks_ruby::deploy line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; ----
STDOUT: 
STDERR: rake aborted!
NameError: uninitialized constant Bullet
/srv/www/<REDACTED>/releases/20180123183147/config/environments/development.rb:45:in `block in <top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/railtie.rb:210:in `instance_eval'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/railtie.rb:210:in `configure'
/srv/www/<REDACTED>/releases/20180123183147/config/environments/development.rb:1:in `<top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:597:in `each'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/engine.rb:597:in `block in <class:Engine>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/srv/www/<REDACTED>/releases/20180123183147/config/environment.rb:5:in `<top (required)>'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/srv/www/<REDACTED>/shared/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
---- End output of case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; ----
Ran case $(sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:version 2>&1") in *"ActiveRecord::NoDatabaseError"*) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:setup";; *) sudo -i -u deploy bash -c "cd $PWD; bundle exec rake db:migrate";; esac; returned 1
[2018-01-23T18:34:08+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
Can anyone help me to discover what am I doing wrong?

best regards,

**Comment by HelioCampos** [comment]
I fixed my problem making the OS link `'/usr/local/bin/bundle'` point to the path `"/home/#{app_user}/.rbenv/shims/bundle"` in the `recipes/setup.rb` file. It could break other applications in the OS if not done thought because other users could not have permission to this directory but in my case, where I use it to deploy on server with only one app in the OS, it doesn't seems a problem for now. I won't make a PR because of this. It someone know another way to do this without break the OS, please, let me know.
```
if node['platform_family'] == 'debian'
  link '/usr/local/bin/bundle' do
    to "/home/#{app_user}/.rbenv/shims/bundle"
  end 
else
  link '/usr/local/bin/bundle' do
    to "/home/#{app_user}/.rbenv/shims/bundle"
  end 
end
```

**Comment by ajgon** [comment]
The idea here is to avoid using ruby versioning tools like `rvm` or `rbenv` at all. Since (by assumption), the AWS environment is not development, there should be always one ruby version installed (the one which is expected in final product). That's why [you have a config option to determine the ruby version](https://opsworks-ruby.readthedocs.io/en/latest/attributes.html#stack-attributes), but that's it.
