### ISSUE TITLE
Sidekiq 6.0 removes -i (--index) and -P (--pidfile) options

### ISSUE THREAD

**Issue by betesh** [ajgon/opsworks_ruby#215]
See https://github.com/mperham/sidekiq/blob/6-0/6.0-Upgrade.md#whats-new and mperham/sidekiq#4065 for more details

Somehow https://github.com/ajgon/opsworks_ruby/blob/v1.14.0/templates/default/sidekiq.monitrc.erb will have to be rewritten to deal with this change.  I'm not sure how.

To this project's credit, the author designed it not to support the -L option, which was also removed in favor of logging only to STDOUT.

### Expected Behavior
Sidekiq starts

### Actual Behavior
Setup succeeds, but sidekiq doesn't start.  The following gets logged to syslog:

```
invalid option: -i
/srv/www/my_app/shared/vendor/bundle/ruby/2.6.0/bundler/gems/sidekiq-702f6b9eb950/lib/sidekiq/cli.rb:352:in `parse_options'
/srv/www/my_app/shared/vendor/bundle/ruby/2.6.0/bundler/gems/sidekiq-702f6b9eb950/lib/sidekiq/cli.rb:208:in `setup_options'
/srv/www/my_app/shared/vendor/bundle/ruby/2.6.0/bundler/gems/sidekiq-702f6b9eb950/lib/sidekiq/cli.rb:24:in `parse'
/srv/www/my_app/shared/vendor/bundle/ruby/2.6.0/bundler/gems/sidekiq-702f6b9eb950/bin/sidekiq:11:in `<top (required)>'
/srv/www/my_app/shared/vendor/bundle/ruby/2.6.0/bin/sidekiq:23:in `load'
/srv/www/my_app/shared/vendor/bundle/ruby/2.6.0/bin/sidekiq:23:in `<main>'
```

### Custom JSON
```json
{
    "ruby-ng": {
        "ruby_version": "2.6"
    },
    "deploy": {
        "my_app": {
            "database": { ...  },
            "worker": {
                "adapter": "sidekiq"
            }
        }
    }
}
```

### Chef log including error
Setup passes, with no errors in log

**Comment by betesh** [comment]
Thanks!

**Comment by betesh** [comment]
I noticed another issue: https://github.com/ajgon/opsworks_ruby/blob/1e9e32b91bed481e4d1ad2f9e4f375631de3f80d/libraries/drivers_worker_sidekiq.rb#L68 -- sidekiq 6 doesn't create the pid file, so sidekiq doesn't get quieted or stopped.

**Comment by betesh** [comment]
I also found this in /var/log/syslog -- it seems that monit fails to stop sidekiq:
```
monit[1054]: 'sidekiq_myappshortname-2' failed to stop (exit status 2) -- '/bin/su - deploy -c \ ps -ax | grep bundle exec sidekiq | grep sidekiq_2.yml | grep -v grep | awk {print $1} | xargs kill\ ': /bin/su: invalid option -- 'a'#012Usage: su [options] [LOGIN]#012#012Options:#012  -c, --command COMMAND         pass COMMAND to the invoked
monit[1054]: 'sidekiq_myappshortname-2' restart action done
```
