### ISSUE TITLE
Column change migrations fails

### ISSUE THREAD

**Issue by neo87cs** [ajgon/opsworks_ruby#290]
### Expected Behavior
We did a migration that is meant to migrate a column from a table to another and update it with a query before dropping the old column. The query requires for 1-2 seconds.

### Actual Behavior
The migration is run by all the 4 instances inside OpsWorks layers, it fails  for 3 and success for one only

### Custom JSON
```json
"database": {
    "adapter": "postgresql",
   ....
},
"framework": {
    "envs_in_console": true,
    "assets_precompile": false
},
"appserver": {
    "log_requests": true
},
"webserver": {
    "proxy_read_timeout": 180,
    "proxy_send_timeout": 180
},
"worker": {
    "adapter": "resque",
    "process_count": 1,
    "queues": "queue_name",
    "workers": 1
}
```

### Chef log including error
```
================================================================================
Error executing action `deploy` on resource 'deploy[hurricane_api]'
================================================================================
 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of case $(/usr/local/bin/bundle exec rake db:version 2>&1) in *"ActiveRecord::NoDatabaseError"*) /usr/local/bin/bundle exec rake db:setup;; *) /usr/local/bin/bundle exec rake db:migrate;; esac ----
STDOUT: `/root` is not writable.
Bundler will use `/tmp/bundler/home/root' as your home directory temporarily.
== 20220712134824 InvertRcaTemporaryDraftRefToDraft: migrating ================
-- add_column(:drafts, :rca_temporary_draft_id, :integer)
STDERR: rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
 
PG::DuplicateColumn: ERROR:  column "rca_temporary_draft_id" of relation "drafts" already exists
: ALTER TABLE "drafts" ADD "rca_temporary_draft_id" integer
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:407:in `add_column'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:434:in `add_column'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:665:in `block in method_missing'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `block in say_with_time'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `say_with_time'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:654:in `method_missing'
/srv/www/hurricane_api/releases/20220726084335/db/migrate/20220712134824_invert_rca_temporary_draft_ref_to_draft.rb:3:in `up'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:611:in `exec_migration'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:591:in `block in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:590:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:768:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1069:in `block in ddl_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1069:in `ddl_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:984:in `block in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `each'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:823:in `up'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:801:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
 
Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "rca_temporary_draft_id" of relation "drafts" already exists
: ALTER TABLE "drafts" ADD "rca_temporary_draft_id" integer
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:407:in `add_column'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:434:in `add_column'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:665:in `block in method_missing'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `block in say_with_time'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `say_with_time'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:654:in `method_missing'
/srv/www/hurricane_api/releases/20220726084335/db/migrate/20220712134824_invert_rca_temporary_draft_ref_to_draft.rb:3:in `up'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:611:in `exec_migration'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:591:in `block in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:590:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:768:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1069:in `block in ddl_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1069:in `ddl_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:984:in `block in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `each'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:823:in `up'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:801:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
 
Caused by:
PG::DuplicateColumn: ERROR:  column "rca_temporary_draft_id" of relation "drafts" already exists
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:407:in `add_column'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:434:in `add_column'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:665:in `block in method_missing'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `block in say_with_time'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `say_with_time'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:654:in `method_missing'
/srv/www/hurricane_api/releases/20220726084335/db/migrate/20220712134824_invert_rca_temporary_draft_ref_to_draft.rb:3:in `up'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:611:in `exec_migration'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:591:in `block in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:590:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:768:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1069:in `block in ddl_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1069:in `ddl_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:984:in `block in migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `each'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:823:in `up'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:801:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/srv/www/hurricane_api/shared/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
---- End output of case $(/usr/local/bin/bundle exec rake db:version 2>&1) in *"ActiveRecord::NoDatabaseError"*) /usr/local/bin/bundle exec rake db:setup;; *) /usr/local/bin/bundle exec rake db:migrate;; esac ----
Ran case $(/usr/local/bin/bundle exec rake db:version 2>&1) in *"ActiveRecord::NoDatabaseError"*) /usr/local/bin/bundle exec rake db:setup;; *) /usr/local/bin/bundle exec rake db:migrate;; esac returned 1
 
Cookbook Trace:
---------------
/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/provider_deploy.rb:196:in `block in migrate'
/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/provider_deploy.rb:194:in `migrate'
/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/provider_deploy.rb:153:in `deploy'
/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/provider_deploy.rb:102:in `block in action_deploy'
/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/provider_deploy.rb:434:in `with_rollback_on_error'
/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/provider_deploy.rb:101:in `action_deploy'
 
Resource Declaration:
---------------------
# In /var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb
 
24:   deploy application['shortname'] do
25:     deploy_to deploy_dir(application)
26:     user node['deployer']['user'] || 'root'
27:     group www_group
28:     environment env_vars
29: 
30:     provider Chef::Provider::Deploy::Revision if globals(:deploy_revision, application['shortname'])
31: 
32:     if globals(:rollback_on_error, application['shortname']).nil?
33:       rollback_on_error node['defaults']['global']['rollback_on_error']
34:     else
35:       rollback_on_error globals(:rollback_on_error, application['shortname'])
36:     end
37: 
 
Compiled Resource:
------------------
# Declared in /var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:24:in `block in from_file'
 
deploy("hurricane_api") do
action [:deploy]
updated true
updated_by_last_action true
retries 0
retry_delay 2
default_guard_interpreter :default
deploy_to "/srv/www/hurricane_api"
environment {"RAILS_ENV"=>"production", "GIT_SSH"=>"/tmp/ssh-git-wrapper.sh"}
repository_cache "cached-copy"
purge_before_symlink ["log", "tmp/cache", "tmp/pids", "public/system", "public/assets"]
create_dirs_before_symlink ["tmp", "public", "config", "../../shared/cache", "../../shared/assets"]
symlink_before_migrate {"config/secrets.yml"=>"config/secrets.yml", "config/slimpay.yml"=>"config/slimpay.yml", "config/initializers/rollbar.rb"=>"config/initializers/rollbar.rb", "config/environments/production.rb"=>"config/environments/production.rb", "config/remote_counter.yml"=>"config/remote_counter.yml", "config/twilio.yml"=>"config/twilio.yml", "config/infocar.yml"=>"config/infocar.yml", "config/signature_features.yml"=>"config/signature_features.yml", "config/initializers/docusign_rest.rb"=>"config/initializers/docusign_rest.rb", "config/email_checker.yml"=>"config/email_checker.yml", "config/aviva.yml"=>"config/aviva.yml", "config/s3.yml"=>"config/s3.yml", "config/previnet_client.yml"=>"config/previnet_client.yml", "config/quantum_client.yml"=>"config/quantum_client.yml", "config/tua_assicurazioni_client.yml"=>"config/tua_assicurazioni_client.yml", "config/resque.yml"=>"config/resque.yml", "config/hubspot/config.yml"=>"config/hubspot/config.yml", "config/air_api.yml"=>"config/air_api.yml", "config/rca.yml"=>"config/rca.yml", "config/database.yml"=>"config/database.yml"}
symlinks {"system"=>"public/system", "assets"=>"public/assets", "cache"=>"tmp/cache", "pids"=>"tmp/pids", "log"=>"log"}
revision "master"
migrate true
remote "origin"
enable_submodules true
scm_provider Chef::Provider::Git
keep_releases 5
enable_checkout true
checkout_branch "deploy"
declared_type :deploy
cookbook_name "opsworks_ruby"
recipe_name "deploy"
user "deploy"
git_ssh_wrapper "/tmp/ssh-git-wrapper.sh"
repo "git@github.com:fit2you/hurricane.git"
migration_command "case $(/usr/local/bin/bundle exec rake db:version 2>&1) in *\"ActiveRecord::NoDatabaseError\"*) /usr/local/bin/bundle exec rake db:setup;; *) /usr/local/bin/bundle exec rake db:migrate;; esac"
before_migrate #<Proc:0x000000026cc760@/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:66>
before_symlink #<Proc:0x000000026df860@/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:76>
before_restart #<Proc:0x000000026de8c0@/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:86>
after_restart #<Proc:0x000000026dddd0@/var/chef/runs/0862a9e7-a653-4bea-a996-421db33e8d01/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/deploy.rb:94>
shared_path "/srv/www/hurricane_api/shared"
destination "/srv/www/hurricane_api/shared/cached-copy"
current_path "/srv/www/hurricane_api/current"
end
 
Platform:
---------
x86_64-linux
 
[2022-07-26T08:44:03+00:00] INFO: Running queued delayed notifications before re-raising exception
[2022-07-26T08:44:03+00:00] DEBUG: Re-raising exception: Mixlib::ShellOut::ShellCommandFailed - deploy[hurricane_api] (opsworks_ruby::deploy line 24) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of case $(/usr/local/bin/bundle exec rake db:version 2>&1) in *"ActiveRecord::NoDatabaseError"*) /usr/local/bin/bundle exec rake db:setup;; *) /usr/local/bin/bundle exec rake db:migrate;; esac ----
STDOUT: `/root` is not writable.
Bundler will use `/tmp/bundler/home/root' as your home directory temporarily.
== 20220712134824 InvertRcaTemporaryDraftRefToDraft: migrating ================
-- add_column(:drafts, :rca_temporary_draft_id, :integer)
STDERR: rake aborted!
```

**Comment by phongsi** [comment]
Hey, since no one has responded to you I just wanted to state my opinion on this issue.

Usually, when deploying simple migrations on all servers one would get a ActiveRecord::ConcurrentMigrationError. There isn't a default smart mechanism to determine how the servers should execute a migration, especially not in the chef cookbooks.

You could just run migrations from 1 server. That's how I normally do schema changes and migrations.

Your migration is obviously  more complicated and includes an update command. I don't know what your sql looks like, but issues like the one you have and others like bulk updates locking the table could occur. I recommend just deploying to one server if you need to migrate. And also to have non breaking changes when you do. For example, add_column and update. Remove the column in a later migration so you dont have multiple processes trying to remove a locked table.

I personally don't think handling this use case directly in opsworks_ruby is the way. Just my opinion.

**Comment by phongsi** [comment]
Hey, since no one has responded to you I just wanted to state my opinion on this issue.

Usually, when deploying simple migrations on all servers one would get a ActiveRecord::ConcurrentMigrationError. There isn't a default smart mechanism to determine how the servers should execute a migration, especially not in the chef cookbooks.

You could just run migrations from 1 server. That's how I normally do schema changes and migrations.

Your migration is obviously more complicated and includes an update command. I don't know what your sql looks like, but issues like the one you have and others like bulk updates locking the table could occur. I recommend just deploying to one server if you need to migrate. And also to have non breaking changes when you do. For example, add_column and update. Remove the column in a later migration so you dont have multiple processes trying to remove a locked table.

I personally don't think handling this use case directly in opsworks_ruby is the way. Just my opinion.
