### ISSUE TITLE
Unicorn does not start on opsworks_ruby::deploy

### ISSUE THREAD

**Issue by ardeearam** [ajgon/opsworks_ruby#82]
Hello,

For some reason, deploying an app does not cause unicorn to start on its own. As a workaround, I manually SSH and execute `/srv/www/app/shared/scripts/unicorn.service start`. However, this is not scalable, and completely defeats the purpose of having chef scripts.

Does anyone experience this as well? Below is the unicorn error log.

```
E, [2017-05-26T08:21:33.480262 #23137] ERROR -- : adding listener failed addr=/srv/www/cloudhealth/shared/sockets/unicorn.sock (in use)
E, [2017-05-26T08:21:33.480342 #23137] ERROR -- : retrying in 0.5 seconds (2 tries left)
E, [2017-05-26T08:21:33.980662 #23137] ERROR -- : adding listener failed addr=/srv/www/cloudhealth/shared/sockets/unicorn.sock (in use)
E, [2017-05-26T08:21:33.980738 #23137] ERROR -- : retrying in 0.5 seconds (1 tries left)
E, [2017-05-26T08:21:34.481058 #23137] ERROR -- : adding listener failed addr=/srv/www/cloudhealth/shared/sockets/unicorn.sock (in use)
E, [2017-05-26T08:21:34.481140 #23137] ERROR -- : retrying in 0.5 seconds (0 tries left)
E, [2017-05-26T08:21:34.981461 #23137] ERROR -- : adding listener failed addr=/srv/www/cloudhealth/shared/sockets/unicorn.sock (in use)
/srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/socket_helper.rb:158:in `initialize': Address already in use - connect(2) for /srv/www/cloudhealth/shared/sockets/unicorn.sock (Errno::EADDRINUSE)
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/socket_helper.rb:158:in `new'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/socket_helper.rb:158:in `bind_listen'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:242:in `listen'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:813:in `block in bind_new_listeners!'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:813:in `each'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:813:in `bind_new_listeners!'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:138:in `start'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/bin/unicorn_rails:209:in `<top (required)>'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
        from /srv/www/cloudhealth/shared/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
I, [2017-05-26T08:21:44.730460 #21789]  INFO -- : reaped #<Process::Status: pid 23049 exit 0> worker=0
I, [2017-05-26T08:22:19.003415 #21789]  INFO -- : master complete
```

**Comment by ajgon** [comment]
This should not happen. Can you paste me your Stack JSON (don't forget to remove sensitive info!). In theory, the old unicorn should be killed, before new boots up. Do you use custom `unicorn.rb` ?

**Comment by interu** [comment]
I also experienced similar in Nginx + Puma.
Although not Unicorn, the possibility of the same phenomenon seems high.
One of puma process remained after deploy. Therefore, new process could not be started.
I executed ``` kill -9 ${Remained puma PID}```
After this, I could restart puma following command.
```
/srv/www/APP_NAME/shared/scripts/puma.service start
```

I think that it is caused by stop processing of appserver.
https://github.com/ajgon/opsworks_ruby/blob/master/templates/default/appserver.service.erb#L50

TERM is better than QUIT for stop the processes.

ref)
https://github.com/puma/puma/blob/5bac8d59710f465bc64140f441d9e1afb1aae473/lib/puma/control_cli.rb#L192

What do you think?
