### ISSUE TITLE
Concurrent Migration Error

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#88]
A long running migration was interrupted during a deployment.  This caused the rails migration advisory lock to never be released.  The only way to release the lock was by restarting the database server.

The interruption came in the form of `SignalException: SIGTERM`.  There were no other opsworks commands running at the time and the deployment timeout is set for a few hours.

Any idea what would have caused the exception?

Here's the tail end of the deployment log:

```
Platform:
---------
x86_64-linux
 
[2017-06-13T22:54:45+00:00] INFO: Running queued delayed notifications before re-raising exception
[2017-06-13T22:54:45+00:00] ERROR: Running exception handlers
[2017-06-13T22:54:45+00:00] ERROR: Exception handlers complete
[2017-06-13T22:54:45+00:00] FATAL: Stacktrace dumped to /var/chef/runs/51202816-3b69-45d4-ae45-5ac1306da490/local-mode-cache/cache/chef-stacktrace.out
[2017-06-13T22:54:45+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-06-13T22:54:45+00:00] ERROR: deploy[app] (opsworks_ruby::deploy line 22) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
Command exceeded allowed execution time, process terminated
---- Begin output of if /usr/local/bin/bundle exec rake db:version > /dev/null 2>&1; then /usr/local/bin/bundle exec rake db:migrate; else /usr/local/bin/bundle exec rake db:setup; fi ----
STDOUT: `/root` is not writable.
Bundler will use `/tmp/bundler/home/root' as your home directory temporarily.
== 20170613163412 ChangeProductAgreementFkToDeleteNullify: migrating - Shard: master 
-- remove_foreign_key(:products, :agreements)
-> 0.0980s
-- add_foreign_key(:products, :agreements, {:on_delete=>:nullify})
STDERR: DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in included at /srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/hair_trigger-df5a91bab0be/lib/hair_trigger/migrator.rb:20)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in included at /srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/hair_trigger-df5a91bab0be/lib/hair_trigger/schema_dumper.rb:100)
rake aborted!
SignalException: SIGTERM
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/abstract_adapter.rb:13:in `instrument'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:916:in `add_foreign_key'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:846:in `block in method_missing'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:815:in `block in say_with_time'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:815:in `say_with_time'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:835:in `method_missing'
/srv/www/app/releases/20170613224420/db/migrate/20170613163412_change_product_agreement_fk_to_delete_nullify.rb:4:in `change'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:789:in `exec_migration'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:772:in `block in migrate'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:771:in `migrate'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:951:in `migrate'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1232:in `block in execute_migration_in_transaction'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1302:in `ddl_transaction'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1231:in `execute_migration_in_transaction'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1203:in `block in migrate_without_lock'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1202:in `each'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1202:in `migrate_without_lock'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1150:in `block in migrate'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1319:in `with_advisory_lock'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1150:in `migrate'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/migration.rb:100:in `migrate_with_octopus'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:1006:in `up'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/migration.rb:127:in `block in up_with_octopus'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:246:in `block (2 levels) in run_queries_on_shard'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:506:in `using_shard'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:245:in `block in run_queries_on_shard'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:489:in `keeping_connection_proxy'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:244:in `run_queries_on_shard'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:253:in `block in send_queries_to_multiple_shards'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:252:in `map'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:252:in `send_queries_to_multiple_shards'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/migration.rb:126:in `up_with_octopus'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/migration.rb:984:in `migrate'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/migration.rb:118:in `block in migrate_with_octopus'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:246:in `block (2 levels) in run_queries_on_shard'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:506:in `using_shard'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:245:in `block in run_queries_on_shard'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:489:in `keeping_connection_proxy'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:244:in `run_queries_on_shard'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:253:in `block in send_queries_to_multiple_shards'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:252:in `map'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/proxy.rb:252:in `send_queries_to_multiple_shards'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/bundler/gems/octopus-b2201fb56028/lib/octopus/migration.rb:117:in `migrate_with_octopus'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/tasks/database_tasks.rb:163:in `migrate'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/srv/www/app/shared/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/cli.rb:335:in `exec'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/cli.rb:11:in `start'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/exe/bundle:32:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.5/exe/bundle:24:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3@global/bin/bundle:22:in `load'
/usr/local/rvm/gems/ruby-2.3.3@global/bin/bundle:22:in `<main>'
/usr/local/rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
---- End output of if /usr/local/bin/bundle exec rake db:version > /dev/null 2>&1; then /usr/local/bin/bundle exec rake db:migrate; else /usr/local/bin/bundle exec rake db:setup; fi ----
Ran if /usr/local/bin/bundle exec rake db:version > /dev/null 2>&1; then /usr/local/bin/bundle exec rake db:migrate; else /usr/local/bin/bundle exec rake db:setup; fi returned 
[2017-06-13T22:54:47+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by ajgon** [comment]
Not sure, but I think Chef sends `SIGTERM` after 600 timeout, notice this line:

```
[2017-06-13T22:54:45+00:00] ERROR: deploy[app] (opsworks_ruby::deploy line 22) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
```

Have you tried to alter the `timeout` parameter in your stack.json? ( `{ "default": { "timeout": <xxx> } }` )

**Comment by databyte** [comment]
You may want to find an alternative entirely by going for [zero-downtime migrations](https://blog.codeship.com/rails-migrations-zero-downtime/). In our environment, we go for split-second migrations. We add the columns we want, setup a script to run the long-running process separately from the deployment and let the application code handle both pre-scripted and post-scripted data until the final release that will remove the old column.

No more failed deployments, no contention over migrations and code rollbacks are easy because database migrations are not altering existing columns and non-destructive.
